[project]
name = "wine-blog-scrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]
